DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRAND;

CREATE TABLE BRAND (
   id INT PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   description VARCHAR(255)
);

CREATE TABLE PRICES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    brand_id INT NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    price_list INT NOT NULL,
    product_id BIGINT NOT NULL,
    priority INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    curr VARCHAR(3) NOT NULL,
    CONSTRAINT FK_BRAND FOREIGN KEY (brand_id) REFERENCES BRAND(id)
);